// Package rationale renders an IR dashboard to reviewer-facing Markdown.
//
// The Markdown document explains why each panel was included, what queries
// it runs, and what was omitted. It is the human half of the DashGen
// review surface: the Grafana JSON answers "what", this answers "why".
//
// Determinism contract: identical IR inputs must produce byte-identical
// Markdown across runs. Sections follow IR slice order. Within a section,
// panels are sorted by UID so the layout is stable even if synthesis
// reshuffles its internal ordering later.
package rationale

import (
	"fmt"
	"sort"
	"strings"

	"dashgen/internal/ir"
)

// toolVersion is emitted in the header so reviewers can correlate a
// rationale file with a DashGen release. Tracked here until the repo has a
// dedicated version package.
const toolVersion = "0.1.0-dev"

// Render produces rationale Markdown for the given IR.
func Render(d *ir.Dashboard) ([]byte, error) {
	if d == nil {
		return nil, fmt.Errorf("rationale: nil dashboard")
	}

	var b strings.Builder
	writeHeader(&b, d)
	writeIncluded(&b, d)
	writeOmitted(&b, d)
	writeDashboardWarnings(&b, d)
	return []byte(b.String()), nil
}

func writeHeader(b *strings.Builder, d *ir.Dashboard) {
	fmt.Fprintf(b, "# %s\n\n", d.Title)
	fmt.Fprintf(b, "- Profile: %s\n", d.Profile)
	fmt.Fprintf(b, "- UID: %s\n", d.UID)
	fmt.Fprintf(b, "- Generated by: DashGen v%s\n\n", toolVersion)
}

func writeIncluded(b *strings.Builder, d *ir.Dashboard) {
	b.WriteString("## Included sections\n\n")
	if len(d.Rows) == 0 {
		b.WriteString("_none_\n\n")
		return
	}
	for _, row := range d.Rows {
		fmt.Fprintf(b, "### %s\n\n", row.Title)
		writeRowBody(b, row)
		b.WriteString("\n")
	}
}

func writeRowBody(b *strings.Builder, row ir.Row) {
	included := make([]ir.Panel, 0, len(row.Panels))
	for _, p := range row.Panels {
		if p.Verdict != ir.VerdictRefuse {
			included = append(included, p)
		}
	}
	if len(included) == 0 {
		b.WriteString("_none_\n")
		return
	}
	sort.SliceStable(included, func(i, j int) bool {
		return included[i].UID < included[j].UID
	})
	for _, p := range included {
		writePanelEntry(b, p)
	}
}

func writePanelEntry(b *strings.Builder, p ir.Panel) {
	fmt.Fprintf(b, "- **%s** (confidence: %.2f) — %s\n", p.Title, p.Confidence, p.Rationale)
	for _, q := range p.Queries {
		warnings := joinCodes(q.WarningCodes)
		fmt.Fprintf(b, "  - query: `%s` — verdict: %s\n", q.Expr, q.Verdict)
		fmt.Fprintf(b, "  - warnings: %s\n", warnings)
	}
}

func writeOmitted(b *strings.Builder, d *ir.Dashboard) {
	b.WriteString("## Omitted\n\n")
	lines := collectOmitted(d)
	if len(lines) == 0 {
		b.WriteString("_none_\n\n")
		return
	}
	for _, line := range lines {
		fmt.Fprintf(b, "- %s\n", line)
	}
	b.WriteString("\n")
}

// collectOmitted gathers refusal explanations for panels and for individual
// query candidates. Rows are never refused at IR level, so row-level
// omission is not emitted. Panels with Verdict=Refuse contribute one line;
// panels that kept some queries but refused others contribute a line per
// refused query. Output is sorted for stability.
func collectOmitted(d *ir.Dashboard) []string {
	lines := make([]string, 0)
	for _, row := range d.Rows {
		for _, p := range row.Panels {
			if p.Verdict == ir.VerdictRefuse {
				reason := panelRefusalReason(p)
				lines = append(lines, fmt.Sprintf("%s / %s: %s", row.Title, p.Title, reason))
				continue
			}
			for _, q := range p.Queries {
				if q.Verdict == ir.VerdictRefuse {
					reason := q.RefusalReason
					if reason == "" {
						reason = "refused"
					}
					lines = append(lines, fmt.Sprintf("%s / %s / `%s`: %s", row.Title, p.Title, q.Expr, reason))
				}
			}
		}
	}
	sort.Strings(lines)
	return lines
}

// panelRefusalReason picks the clearest refusal explanation available for a
// refused panel. It prefers the panel rationale (which synthesis is
// expected to populate with the reason) and falls back to the first
// refused query's RefusalReason.
func panelRefusalReason(p ir.Panel) string {
	if p.Rationale != "" {
		return p.Rationale
	}
	for _, q := range p.Queries {
		if q.Verdict == ir.VerdictRefuse && q.RefusalReason != "" {
			return q.RefusalReason
		}
	}
	return "refused"
}

func writeDashboardWarnings(b *strings.Builder, d *ir.Dashboard) {
	b.WriteString("## Dashboard-level warnings\n\n")
	if len(d.Warnings) == 0 {
		b.WriteString("_none_\n")
		return
	}
	sorted := append([]string{}, d.Warnings...)
	sort.Strings(sorted)
	for _, w := range sorted {
		code, detail := splitWarning(w)
		if detail == "" {
			fmt.Fprintf(b, "- %s\n", code)
		} else {
			fmt.Fprintf(b, "- %s: %s\n", code, detail)
		}
	}
}

// splitWarning accepts either a bare code or a "code: detail" string. The
// IR stores dashboard warnings as opaque strings, so this is the seam
// between storage and rendering.
func splitWarning(s string) (string, string) {
	if i := strings.Index(s, ":"); i >= 0 {
		return strings.TrimSpace(s[:i]), strings.TrimSpace(s[i+1:])
	}
	return s, ""
}

func joinCodes(codes []string) string {
	if len(codes) == 0 {
		return "none"
	}
	sorted := append([]string{}, codes...)
	sort.Strings(sorted)
	return strings.Join(sorted, ", ")
}
