package rationale

import (
	"bytes"
	"strings"
	"testing"

	"dashgen/internal/ir"
)

func fixtureDashboard() *ir.Dashboard {
	return &ir.Dashboard{
		UID:     "d1d2d3d4",
		Title:   "Payments Service",
		Profile: "service",
		Rows: []ir.Row{
			{
				Title: "traffic",
				Panels: []ir.Panel{
					{
						UID:        "aaaaaaaa11112222",
						Title:      "Requests per second",
						Kind:       ir.PanelKindTimeSeries,
						Unit:       "reqps",
						Confidence: 0.92,
						Verdict:    ir.VerdictAccept,
						Rationale:  "primary RED traffic signal",
						Queries: []ir.QueryCandidate{
							{
								Expr:         "sum(rate(http_requests_total[5m]))",
								LegendFormat: "rps",
								Verdict:      ir.VerdictAccept,
							},
						},
					},
					{
						UID:        "bbbbbbbb33334444",
						Title:      "Requests by method",
						Kind:       ir.PanelKindTimeSeries,
						Unit:       "reqps",
						Confidence: 0.70,
						Warnings:   []string{"high_cardinality_group"},
						Verdict:    ir.VerdictAcceptWithWarning,
						Rationale:  "method grouping has moderate cardinality",
						Queries: []ir.QueryCandidate{
							{
								Expr:         "sum by (method) (rate(http_requests_total[5m]))",
								LegendFormat: "{{method}}",
								Verdict:      ir.VerdictAcceptWithWarning,
								WarningCodes: []string{"high_cardinality_group"},
							},
							{
								Expr:          "sum by (user_id) (rate(http_requests_total[5m]))",
								Verdict:       ir.VerdictRefuse,
								RefusalReason: "banned high-cardinality label user_id",
							},
						},
					},
				},
			},
			{
				Title: "errors",
				Panels: []ir.Panel{
					{
						UID:        "cccccccc55556666",
						Title:      "Error rate",
						Kind:       ir.PanelKindStat,
						Unit:       "percentunit",
						Confidence: 0.88,
						Verdict:    ir.VerdictAccept,
						Rationale:  "5xx share of total traffic",
						Queries: []ir.QueryCandidate{
							{
								Expr:    `sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))`,
								Verdict: ir.VerdictAccept,
							},
						},
					},
					{
						UID:        "dddddddd77778888",
						Title:      "Errors by trace_id",
						Kind:       ir.PanelKindTimeSeries,
						Unit:       "short",
						Confidence: 0.20,
						Verdict:    ir.VerdictRefuse,
						Rationale:  "grouping by trace_id refused",
						Queries: []ir.QueryCandidate{
							{
								Expr:          "sum by (trace_id) (rate(http_requests_total[5m]))",
								Verdict:       ir.VerdictRefuse,
								RefusalReason: "banned high-cardinality label trace_id",
							},
						},
					},
				},
			},
		},
		Warnings: []string{"selector_wildcard: one metric selector had no label filter"},
	}
}

func TestRenderDeterministic(t *testing.T) {
	d := fixtureDashboard()
	a, err := Render(d)
	if err != nil {
		t.Fatalf("first render: %v", err)
	}
	b, err := Render(d)
	if err != nil {
		t.Fatalf("second render: %v", err)
	}
	if !bytes.Equal(a, b) {
		t.Fatalf("render not byte-stable across runs\nfirst:\n%s\nsecond:\n%s", a, b)
	}
}

func TestRenderGolden(t *testing.T) {
	want := `# Payments Service

- Profile: service
- UID: d1d2d3d4
- Generated by: DashGen v0.1.0-dev

## Included sections

### traffic

- **Requests per second** (confidence: 0.92) — primary RED traffic signal
  - query: ` + "`sum(rate(http_requests_total[5m]))`" + ` — verdict: accept
  - warnings: none
- **Requests by method** (confidence: 0.70) — method grouping has moderate cardinality
  - query: ` + "`sum by (method) (rate(http_requests_total[5m]))`" + ` — verdict: accept_with_warning
  - warnings: high_cardinality_group
  - query: ` + "`sum by (user_id) (rate(http_requests_total[5m]))`" + ` — verdict: refuse
  - warnings: none

### errors

- **Error rate** (confidence: 0.88) — 5xx share of total traffic
  - query: ` + "`sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))`" + ` — verdict: accept
  - warnings: none

## Omitted

- errors / Errors by trace_id: grouping by trace_id refused
- traffic / Requests by method / ` + "`sum by (user_id) (rate(http_requests_total[5m]))`" + `: banned high-cardinality label user_id

## Dashboard-level warnings

- selector_wildcard: one metric selector had no label filter
`

	d := fixtureDashboard()
	got, err := Render(d)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if string(got) != want {
		t.Fatalf("rationale mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderEmptyDashboard(t *testing.T) {
	d := &ir.Dashboard{
		UID:     "empty",
		Title:   "Empty",
		Profile: "service",
	}
	out, err := Render(d)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	s := string(out)
	if !strings.Contains(s, "## Included sections\n\n_none_") {
		t.Errorf("empty dashboard should render _none_ for sections, got:\n%s", s)
	}
	if !strings.Contains(s, "## Omitted\n\n_none_") {
		t.Errorf("empty dashboard should render _none_ for omissions, got:\n%s", s)
	}
	if !strings.Contains(s, "## Dashboard-level warnings\n\n_none_") {
		t.Errorf("empty dashboard should render _none_ for warnings, got:\n%s", s)
	}
}

func TestRenderNilDashboard(t *testing.T) {
	if _, err := Render(nil); err == nil {
		t.Fatalf("expected error for nil dashboard")
	}
}
